// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJZbe2fjsbfX2ze1UIiOcn11X7EKrvGbo',
    appId: '1:598444938431:web:2c10e496621202ce75220a',
    messagingSenderId: '598444938431',
    projectId: 'flutter-login-signup-demo',
    authDomain: 'flutter-login-signup-demo.firebaseapp.com',
    storageBucket: 'flutter-login-signup-demo.firebasestorage.app',
    measurementId: 'G-7ZNDEW0BSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6y1gKw6_7blKTPbH_RI_ys-LA6I1OcM',
    appId: '1:598444938431:android:976d35034e6a8e1675220a',
    messagingSenderId: '598444938431',
    projectId: 'flutter-login-signup-demo',
    storageBucket: 'flutter-login-signup-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuDMQDh7q23gQThVGAIhLfKUcFHHYWg_s',
    appId: '1:598444938431:ios:2364a28383c1319175220a',
    messagingSenderId: '598444938431',
    projectId: 'flutter-login-signup-demo',
    storageBucket: 'flutter-login-signup-demo.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuDMQDh7q23gQThVGAIhLfKUcFHHYWg_s',
    appId: '1:598444938431:ios:2364a28383c1319175220a',
    messagingSenderId: '598444938431',
    projectId: 'flutter-login-signup-demo',
    storageBucket: 'flutter-login-signup-demo.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJZbe2fjsbfX2ze1UIiOcn11X7EKrvGbo',
    appId: '1:598444938431:web:a520234e7f4b45a875220a',
    messagingSenderId: '598444938431',
    projectId: 'flutter-login-signup-demo',
    authDomain: 'flutter-login-signup-demo.firebaseapp.com',
    storageBucket: 'flutter-login-signup-demo.firebasestorage.app',
    measurementId: 'G-1SD5JE46BN',
  );
}
